### ISSUE TITLE
W zasadzie po co ten interfejs?

### ISSUE THREAD

**Issue by sikorskl** [RafalDardzinski/UsersServer#3]
Masz interfejs dla repozytorium i to jest dobre. Ale w zasadzie gdzie on jest wykorzystywany oprocz tego ze klasa go implementuje? Wszedzie uzywasz implementacji, a nie interfejsu. 

https://github.com/RafalDardzinski/UsersServer/blob/65939c8da691c4b378e6b267667cb9cc3beff845/IRepository.cs#L9

**Comment by RafalDardzinski** [comment]
Wyszedłem z założenia że interfejs ma zdefiniować metody jakie musi zaimplementować repozytorium (podstawowe operacje CRUD) oraz że skoro implementuje go klasa abstrakcyjna Repository, to wszystkie konkretne repozytoria pośrednio także będą ten interfejs implementowały (jako że dziedziczą po Repository). Czy zatem powinienem zrezygnować z interfejsu, czy używać go zamiast implementacji? Jeśli to drugie, to byłbym wdzięczny gdybyś mógł mi podać konkretny przykład.
